
const PrivacyPolicyPage = () => {
  return (
    <main className="container mx-auto px-4 py-16 mt-20">
      <div className="max-w-4xl mx-auto prose lg:prose-xl">
        <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>
        
        <p className="text-sm text-muted-foreground">Last updated: July 26, 2024</p>

        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Interpretation and Definitions</h2>
        <h3 className="text-xl font-bold mt-6 mb-2">Interpretation</h3>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
        
        <h3 className="text-xl font-bold mt-6 mb-2">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
            <li><strong>Application</strong> means the web application named "KEF Sponsor a Dream", a prototype developed for the KEF Alumni Hack-a-thon.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to the developers of this prototype.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. For this Application, no personal data is collected.</li>
            <li><strong>Service</strong> refers to the Application.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself. For this prototype, no usage data is tracked or stored.</li>
            <li><strong>You</strong> mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 className="text-2xl font-bold mt-8 mb-4">Collection and Use of Your Personal Data</h2>
        <h3 className="text-xl font-bold mt-6 mb-2">Types of Data Collected</h3>
        <p><strong>This is a prototype application. We do not collect, store, or process any Personal Data from our users.</strong> All features, including the interactive game, are simulated and do not require any personal information to function.</p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Children's Privacy</h2>
        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone. As this is a prototype, no data collection of any kind occurs.</p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Links to Other Websites</h2>
        <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
        <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Changes to this Privacy Policy</h2>
        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

        <h2 className="text-2xl font-bold mt-8 mb-4">Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, you can understand that this is a non-functional prototype and this policy is for demonstration purposes only.</p>
      </div>
    </main>
  );
};

export default PrivacyPolicyPage;
